const {
    createProject,
    createWorkingFolderFromTemplate,
    deleteFile,
    listRepositoryFiles,
    listTopLevelFolders,
    loadFile,
    loadProjectAsset,
    loadProject,
    loadProjectConfig,
    loadProjectRoot,
    moveFiles,
    saveProjectConfig,
    watchProject,
} = require('./local_git_service_core')

module.exports = {
    createProject,
    createWorkingFolderFromTemplate,
    deleteFile,
    listRepositoryFiles,
    listTopLevelFolders,
    loadFile,
    loadProjectAsset,
    loadProject,
    loadProjectConfig,
    loadProjectRoot,
    moveFiles,
    saveProjectConfig,
    watchProject,
}
